### ISSUE TITLE
🔨 [FE] 1차 배포 수정

### ISSUE THREAD

**Issue by wonhee126** [AgileHub-DQ/Frontend#29]
**🔨 Describe**
feat/27 코드가 merge 안 된 부분이 있음

**✅ Tasks**

- [x] 타임라인-> 검색 기능
- [x] 타임라인 -> 프로젝트 이름 출력
- [x] 스프린트-> 댓글 기능(수정만)
- [x] 백로그 페이지 -> 할당하기
- [x] 메뉴바에서 자유 이동
- [ ] 마이페이지&프로젝트 페이지 다르게 표시
- [ ] 타임라인 아이콘 크기 설정
- [ ] mypage: 프로젝트 삭제, 이슈 생성 주석, 백로그 페이지 주석
- [ ] member: 프로젝트 키 받아오도록 수정

해야 할 것: 

**🙋🏻 More**
더 하고 싶은 말이 있다면 작성해 주세요.
