### ISSUE TITLE
✨[FE] 로그인 페이지

### ISSUE THREAD

**Issue by wonhee126** [AgileHub-DQ/Frontend#5]
**✨ Describe**
로그인 페이지 작업 브랜치

**✅ Tasks**
- [x] 로고 & 카카오로그인 구현
- [x] 3페이지 자동 슬라이드 구현 (라이브러리)
- [ ] 카카오톡 로그인 코드 구현
- [ ] 로그인 성공 시 백로그 페이지로 이동

**🙋🏻 More**
더 하고 싶은 말이 있다면 작성해 주세요.
