### ISSUE TITLE
✨[FE] 프로젝트 생성 페이지 

### ISSUE THREAD

**Issue by drimh** [AgileHub-DQ/Frontend#6]
**✨ Describe**
프로젝트 생성 페이지입니다. 

**✅ Tasks**
- [ ] 하나의 '프로젝트 생성' 페이지로 구현하기 
- [ ] 프로젝트 이름 input 받기 
- [ ] 프로젝트 키 input 받을 때 프론트 단에서 유효성 검사 하기 
- [ ] component - Nav, Title, Input, Button으로 나누기 

**🙋🏻 More**
없슈

**Comment by drimh** [comment]
400  -> 통신 코드 헤더까지 명시할 것.
